### ISSUE TITLE
Reporte de la Entrevista de Gestión de Proyectos de Software

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/entrevista-entrevista-gestion-de-proyecto#2]
[Entrevista.pdf](https://github.com/SistemasTecTlaxiaco/entrevista-entrevista-gestion-de-proyecto/files/7149891/Entrevista.pdf)

**Comment by dulce-blm** [comment]
Calificación 20 puntos.

**Comment by dulce-blm** [comment]
Calificación 20 puntos.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
